services:
  web:
    build: .  
    container_name: docker_app
    restart: always
    volumes:
      - .:/app  
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command:
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py create_superuser &&
      python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresadmin22
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
